apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    spec:
      containers:
      - name: container-countdown
        image: fedora:latest
        command: ["sleep", "5"]
      restartPolicy: Never